
SELECT CPF, NOME, BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

-- USANDO ALIAS PARA AS COLUNAS
SELECT CPF AS IDENTIFICADOR, NOME AS [NOME DE CLIENTE], BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

-- USANDO ALIAS PARA A TABELA
SELECT CPF AS IDENTIFICADOR, NOME AS [NOME DE CLIENTE], BAIRRO, CIDADE FROM TABELA_DE_CLIENTES TDC;

-- USANDO ALIAS PARA DIFERENCIAR AS COLUNAS DE OUTRA TABELA, POR EXEMPLO
SELECT TDC.CPF, TDC.NOME, TDC.BAIRRO FROM TABELA_DE_CLIENTES TDC;

SELECT TDC.* FROM TABELA_DE_CLIENTES TDC;

-- SEM O ALIAS
SELECT TABELA_DE_CLIENTES.CPF, TABELA_DE_CLIENTES.NOME FROM TABELA_DE_CLIENTES;