-- ATRIBUINDO VALORES COM SELECT

DECLARE @CPF VARCHAR(50);
DECLARE @NOME VARCHAR(100);
DECLARE @DATA_NASCIMENTO DATE;
DECLARE @IDADE INT;

SET @CPF = '19290992743'

--SELECT * FROM [TABELA DE CLIENTES]
--WHERE CPF = '19290992743';

-- SUBTITUIÇÃO

--SELECT * FROM [TABELA DE CLIENTES]
--WHERE CPF = @CPF;

-- COLOCANDO VALORES NAS VARIAVEIS

SELECT @NOME = NOME, @DATA_NASCIMENTO = [DATA DE NASCIMENTO], @IDADE = IDADE 
FROM [TABELA DE CLIENTES] 
WHERE CPF = @CPF;

PRINT @NOME;
PRINT @DATA_NASCIMENTO;
PRINT @IDADE;

-- EXERCÍCIO
DECLARE @NUMNOTAS INT

SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS]
WHERE DATA = '01/01/2017';

PRINT @NUMNOTAS

-- USANDO FUNÇÕES NO COMANDO PRINT

--SELECT NOME, CHARINDEX(' ', NOME), SUBSTRING(NOME, 1, CHARINDEX(' ', NOME)-1) 
--FROM [TABELA DE CLIENTES];

PRINT 'O primeiro nome do cliente ' + @NOME + ', cujo CPF é ' + @CPF + ', corresponde a ' + SUBSTRING(@NOME, 1, CHARINDEX(' ', @NOME)-1)