-- CHECK

CREATE TABLE TAB_CHECK
(ID INT NOT NULL,
NOME VARCHAR(50) NULL,
IDADE INT NULL,
CIDADE VARCHAR(50) NULL,
CONSTRAINT CHK_IDADE CHECK (IDADE >= 18));

INSERT INTO TAB_CHECK VALUES (
    1, 'JOÃO', 19, 'RIO DE JANEIRO'
);

INSERT INTO TAB_CHECK VALUES (
    2, 'PEDRO', 16, 'RIO DE JANEIRO'
);

SELECT * FROM TAB_CHECK;