-- FAZENDO CONSULTAS

-- SELECIONANDO TUDO DA TABELA DE PRODUTOS

SELECT * FROM [TABELA DE PRODUTOS];

-- SELECIONANDO TUDO DA TABELA DE CLIENTES

SELECT * FROM [TABELA DE CLIENTES];

-- SELECIONANDO NOME E ESTADO DA TABELA DE CLIENTES

SELECT NOME, ESTADO FROM [TABELA DE CLIENTES];

-- SELECIONANDO NOME E ESTADO DA TABELA DE CLIENTES, EM ORDEM ALFABETICA

SELECT NOME, ESTADO FROM [TABELA DE CLIENTES]
ORDER BY NOME;

-- APELIDANDO COLUNAS

SELECT NOME AS [NOME DO CLIENTE], CPF, ESTADO AS UF FROM [TABELA DE CLIENTES];

-- DESAFIO CONSULTA DOS VENDEDORES

SELECT MATRICULA AS IDENTIFICADOR, [NOME DO VENDEDOR] FROM [TABELA DE VENDEDORES];

-- SELEÇÃO DISTINTA

SELECT DISTINCT SABOR FROM [TABELA DE PRODUTOS];

-- APLICANDO FILTROS

SELECT NOME AS [NOME DO CLIENTE], ESTADO AS UF, [PRIMEIRA COMPRA] FROM [TABELA DE CLIENTES]
WHERE [PRIMEIRA COMPRA] = 1;

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [PRECO DE LISTA] >= 7
ORDER BY [PRECO DE LISTA];

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [PRECO DE LISTA] <= 7
ORDER BY [PRECO DE LISTA];

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [EMBALAGEM] > 'Lata'; -- Ordenação alfabética

SELECT NOME, [DATA DE NASCIMENTO] FROM [TABELA DE CLIENTES]
WHERE [DATA DE NASCIMENTO] > '1995-12-31';

SELECT NOME, [DATA DE NASCIMENTO] FROM [TABELA DE CLIENTES]
WHERE YEAR ([DATA DE NASCIMENTO]) > '1995';

-- CONDIÇÕES COMBINADAS

SELECT NOME, BAIRRO FROM [TABELA DE CLIENTES]
WHERE BAIRRO = 'Copacabana' OR BAIRRO = 'Tijuca';

SELECT NOME, ESTADO, [PRIMEIRA COMPRA] FROM [TABELA DE CLIENTES]
WHERE ESTADO = 'SP' AND [PRIMEIRA COMPRA] = 1;

-- EXERCÍCIO

SELECT [NOME DO VENDEDOR], [PERCENTUAL DE COMISSAO] FROM [TABELA DE VENDEDORES]
WHERE [PERCENTUAL DE COMISSAO] <= 0.08;

SELECT [NOME DO PRODUTO], EMBALAGEM, [PRECO DE LISTA] FROM [TABELA DE PRODUTOS]
WHERE [PRECO DE LISTA] < 6 AND EMBALAGEM = 'Lata';

SELECT NOME, ESTADO FROM [TABELA DE CLIENTES]
WHERE NOT (ESTADO != 'SP' OR ESTADO != 'RJ');

-- ALTERANDO AS INFORMAÇÕES

-- 10% de desconto em sucos com a embalagem Lata
UPDATE [TABELA DE PRODUTOS]
SET [PRECO DE LISTA] = [PRECO DE LISTA] * 0.9
WHERE EMBALAGEM = 'Lata';

UPDATE [TABELA DE PRODUTOS]
SET [PRECO DE LISTA] = 8.10, EMBALAGEM = 'Garrafa'
WHERE [CODIGO DO PRODUTO] = '1088126';

UPDATE [TABELA DE CLIENTES]
SET COMPLEMENTO = ''
WHERE CPF = '1471156710';

-- DELETANDO
DELETE FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '1004327';

SELECT * FROM [TABELA DE CLIENTES];