-- CRIANDO AS TABELAS DO BANCO

/*Colunas:
CPF;
Nome completo;
Endereço completo;
Data de nascimento;
Idade;
Sexo;
Limite de crédito;
Volume mínimo de compra de produto;
Se já realizou alguma compra na empresa.*/

CREATE TABLE [TABELA DE CLIENTES](

CPF CHAR (11),
NOME VARCHAR (50),
RUA VARCHAR (50),
COMPLEMENTO VARCHAR (50),
BAIRRO VARCHAR (50),
ESTADO CHAR (2),
CEP CHAR (8),
[DATA DE NASCIMENTO] DATE,
IDADE SMALLINT,
SEXO CHAR (1),
[LIMITE DE CREDITO] MONEY,
[VOLUME MINIMO] FLOAT,
[PRIMEIRA COMPRA] BIT -- Valor booleano


);

/*Colunas:
código do produto;
nome do produto;
embalagem;
tamanho;
sabor;
preço de lista.
*/

CREATE TABLE [TABELA DE PRODUTOS](

[CODIGO DO PRODUTO] VARCHAR (20) NOT NULL PRIMARY KEY,
[NOME DO PRODUTO] VARCHAR (50),
EMBALAGEM VARCHAR (20),
TAMANHO VARCHAR (20),
SABOR VARCHAR (20),
[PRECO DE LISTA] SMALLMONEY

);

-- ALTERANDO COLUNA

ALTER TABLE [TABELA DE CLIENTES] ALTER COLUMN CPF CHAR (11) NOT NULL;

ALTER TABLE [TABELA DE CLIENTES] ADD CONSTRAINT PK_TABELA_CLIENTE
PRIMARY KEY CLUSTERED (CPF);

-- EXERCÍCIO: TABELA VENDEDORES

CREATE TABLE [TABELA DE VENDEDORES](

MATRICULA CHAR (5) NOT NULL PRIMARY KEY,
[NOME DO VENDEDOR] VARCHAR (100),
[PERCENTUAL DE COMISSAO] FLOAT,

);