-- CRIANDO A BASE DE DADOS

CREATE DATABASE [VENDAS SUCOS];

-- ESPECIFICANDO PROPRIEDADES
CREATE DATABASE [VENDAS SUCOS 2]
ON(
NAME = 'VENDAS_SUCOS_2_DAT', -- ARQUIVO LÓGICO
FILENAME = 'C:\Windows\VENDAS_SUCOS_02.MDF',
SIZE = 10, -- TAMANHO INICIAL
MAXSIZE = 50, -- TAMANHO MAXIMO
FILEGROWTH = 5 -- CRESCIMENTO
)
LOG ON( -- ESPECIFICANDO O ARQUIVO LOG
NAME = 'VENDAS_SUCOS_2_LOG', 
FILENAME = 'C:\Windows\VENDAS_SUCOS_02.LDF',
SIZE = 10, 
MAXSIZE = 50, 
FILEGROWTH = 5 
);

-- EXCLUINDO O BANCO
DROP DATABASE [VENDAS SUCOS 2];
