-- CURSOR

DECLARE @NOME VARCHAR(200);

DECLARE CURSOR1 CURSOR FOR SELECT TOP 4 NOME FROM [TABELA DE CLIENTES]
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 INTO @NOME 
WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT @NOME
	FETCH NEXT FROM CURSOR1 INTO @NOME
END

-- EXERCÍCIO

SELECT NOME, [PERCENTUAL COMISSÃO]
    FROM [TABELA DE VENDEDORES]

DECLARE @NOME2 VARCHAR(200);
DECLARE @COMISSAO FLOAT;

DECLARE CURSOR2 CURSOR FOR SELECT NOME, [PERCENTUAL COMISSÃO] FROM [TABELA DE VENDEDORES]
OPEN CURSOR2
FETCH NEXT FROM CURSOR2 INTO @NOME2, @COMISSAO
WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT @NOME2
	FETCH NEXT FROM CURSOR2 INTO @NOME2, @COMISSAO
END