-- DISTINCT

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Maca';

-- SELECIONA APENAS AS COMBINAÇÕES
SELECT DISTINCT EMBALAGEM, SABOR FROM TABELA_DE_PRODUTOS;

-- EXERCÍCIO

SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS;
-- OU
SELECT COUNT(DISTINCT SABOR) FROM TABELA_DE_PRODUTOS;