-- EXPRESSÕES LÓGICAS

SELECT * FROM TABELA_DE_PRODUTOS;

-- AND
SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Manga' AND TAMANHO = '470 ML';

-- OR
SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Manga' OR TAMANHO = '470 ML';

-- NOT
SELECT * FROM TABELA_DE_PRODUTOS
WHERE NOT (SABOR = 'Manga' OR TAMANHO = '470 ML'); -- USAR O PARENTESES PARA DEFINIR A EXPRESSAO

-- USANDO VARIAS EXPRESSÕES JUNTAS
SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Manga' OR SABOR = 'Laranja' OR SABOR = 'Melancia';

-- OUTRA FORMA
SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR IN ('Manga','Laranja','Melancia');

SELECT * FROM TABELA_DE_PRODUTOS
WHERE (SABOR IN ('Manga','Laranja','Melancia')) AND TAMANHO = '1 Litro';

SELECT * FROM TABELA_DE_CLIENTES
WHERE CIDADE IN ('Rio de Janeiro', 'Sao Paulo') AND (IDADE >= 20 AND IDADE <= 25);

-- USANDO BETWEEN
SELECT * FROM TABELA_DE_CLIENTES
WHERE CIDADE IN ('Rio de Janeiro', 'Sao Paulo') AND (IDADE BETWEEN 20 AND 25);

--USANDO LIKE
SELECT * FROM TABELA_DE_CLIENTES
WHERE NOME LIKE '%Silva%';

SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR IN ('Lima/Limao','Morango/Limao');

-- USANDO O LIKE PARA TER O MESMO RESULTADO
SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR LIKE '%Limao';

SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR LIKE '%Maca%';

SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR LIKE 'Morango%';