-- FUNÇÕES

-- FUNÇÕES DA DATA E HORA

-- DATA DA MÁQUINA
SELECT GETDATE();

-- DATA DE 10 DIAS A FRENTE DA DATA DA MÁQUINA
SELECT DATEADD(DAY, 10, GETDATE());

-- DATA DE 48 DIAS ATRAS DA DATA DA MAQUINA
SELECT DATEADD(DAY, -48, GETDATE());

-- QUANTOS DIAS SE PASSARAM DESDE O 1 DIA DO ANO
SELECT DATEDIFF(DAY, '2024-01-01', GETDATE());

-- SELECIONANDO O DIA DA DATA DA MAQUINA
SELECT DATEPART(DAY, GETDATE());

-- TESANDO DATA VALIDA OU NAO
SELECT ISDATE(DATETIMEFROMPARTS(2022, 02, 28, 00, 00, 00, 00));

-- EXERCÍCIO
SELECT NOME + ' nasceu em ' + 
DATENAME (WEEKDAY,DATA_DE_NASCIMENTO) + ',' +
DATENAME (DAY,DATA_DE_NASCIMENTO) + ' de ' +
DATENAME(MONTH, DATA_DE_NASCIMENTO) + ' de ' +
DATENAME(YEAR, DATA_DE_NASCIMENTO) AS DATA_EXTENSO
FROM TABELA_DE_CLIENTES;