-- FUNÇÕES

-- FUNÇÕES NUMERICAS

-- ARREDONDAMENTO SELECIONANDO AS CASAS DECIMAIS
SELECT ROUND(3.4785, 2), ROUND(3.4735, 2);

-- ARREDONDAMENTO PARA CIMA DE NUMEROS INTEIROS 
SELECT CEILING(3.45);

-- ARREDONDAMENTO PARA BAIXO DE NUMEROS INTEIROS 
SELECT FLOOR(3.45);

-- POTENCIA
SELECT POWER(12, 2);

-- EXPONENCIAL
SELECT EXP(3);

-- RAIZ
SELECT SQRT(300);

-- NUMERO ABSOLUTO
SELECT ABS(10), ABS(-10);

-- DESAFIO
SELECT YEAR(DATA_VENDA) AS ANO, FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO))) 
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF 
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY YEAR(DATA_VENDA);