-- FUNÇÕES

-- FUNÇÕES DE TEXTO

SELECT * FROM TABELA_DE_CLIENTES;

-- MINUSCULAS
SELECT NOME, LOWER(NOME) AS NOME_MINUSCULO FROM TABELA_DE_CLIENTES;

--MAIUSCULAS
SELECT NOME, UPPER(NOME) AS NOME_MAIUSCULO FROM TABELA_DE_CLIENTES;

-- CONCATENAÇÃO
SELECT NOME, CONCAT(ENDERECO_1, ' ', BAIRRO, ' ', CIDADE, ' ', ESTADO, ' - ', CEP) AS ENDERECO_COMPLETO
FROM TABELA_DE_CLIENTES;
-- OUTRA FORMA
SELECT NOME, ENDERECO_1 + ' ' + BAIRRO + ' ' + CIDADE + ' ' + ESTADO + ' - ' + CEP AS ENDERECO_COMPLETO
FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_PRODUTOS;

-- 3 PRIMEIROS CARACTERES
SELECT NOME_DO_PRODUTO, LEFT(NOME_DO_PRODUTO, 3) AS TER_PRIMEIROS_CHAR FROM TABELA_DE_PRODUTOS;

-- SUBSTITUINDO CHAR
SELECT TAMANHO, REPLACE(REPLACE(TAMANHO, 'Litros', 'L'),'Litro', 'L') AS TAMANHO_MODIFICADO FROM TABELA_DE_PRODUTOS;

-- EXERCÍCIO
-- 1 NOME DE CADA CLIENTE

-- Primeiro, vamos localizar o primeiro espaço do nome. 
-- Sua posição. Para isso, basta executar a função CHARINDEX
SELECT NOME, CHARINDEX(' ', NOME, 1) FROM TABELA_DE_CLIENTES;

-- Usando a função SUBSTRING podemos buscar parte do texto que compõe o nome completo 
-- buscando da posição 1 a posição do primeiro espaço.
SELECT NOME, SUBSTRING(NOME, 1, CHARINDEX(' ', NOME, 1)) FROM TABELA_DE_CLIENTES;