-- FUNÇÕES QUE RETORNAM TABELA

SELECT * FROM [NOTAS FISCAIS]

CREATE FUNCTION ListaNotasCliente(@CPF AS VARCHAR(11))
RETURNS TABLE
AS
	RETURN SELECT * FROM [NOTAS FISCAIS] WHERE CPF = @CPF;


SELECT * FROM [dbo].[ListaNotasCliente]('7771579779');