-- FUNÇÕES: CRIANDO UM LOOP

DECLARE @LIMITE_MINIMO INT, @LIMITE_MAXIMO INT;
DECLARE @TABELA_NUMEROS TABLE ([NUMERO] INT, [STATUS] VARCHAR(200), FATURAMENTO FLOAT);
DECLARE @CONTADOR_NOTAS INT;

SET @LIMITE_MINIMO = 1;
SET @LIMITE_MAXIMO = 100000;

SET NOCOUNT ON;

WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
	SELECT @CONTADOR_NOTAS = COUNT(*) FROM [NOTAS FISCAIS] WHERE NUMERO = @LIMITE_MINIMO
	IF @CONTADOR_NOTAS > 0
		BEGIN
			INSERT INTO @TABELA_NUMEROS VALUES (@LIMITE_MINIMO, 'É nota fiscal', dbo.FaturamentoNota(@LIMITE_MINIMO));
		END
	ELSE
		BEGIN
			INSERT INTO @TABELA_NUMEROS VALUES (@LIMITE_MINIMO, 'Não é nota fiscal', 0);
		END
	SET @LIMITE_MINIMO = @LIMITE_MINIMO + 1

END;

SELECT * FROM @TABELA_NUMEROS ORDER BY NUMERO


