-- GROUP BY
SELECT * FROM TABELA_DE_CLIENTES;

SELECT CIDADE, AVG(IDADE) AS IDADE FROM TABELA_DE_CLIENTES
GROUP BY CIDADE; -- NÃO ENTRA O CAMPO IDADE

SELECT CIDADE, AVG(IDADE) AS IDADE, AVG(LIMITE_DE_CREDITO) AS CREDITO FROM TABELA_DE_CLIENTES
GROUP BY CIDADE;

-- APLICANDO UM CONTADOR
SELECT CIDADE, COUNT(*) AS NUMERO_DE_CLIENTES FROM TABELA_DE_CLIENTES
GROUP BY CIDADE;

SELECT EMBALAGEM, COUNT(*) AS NUMERO_DE_PRODUTOS FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Laranja'
GROUP BY EMBALAGEM;

-- EXERCICIO

SELECT * FROM ITENS_NOTAS_FISCAIS
WHERE CODIGO_DO_PRODUTO = 1101035
ORDER BY QUANTIDADE DESC;

SELECT CODIGO_DO_PRODUTO, COUNT(*) AS VENDAS FROM ITENS_NOTAS_FISCAIS
WHERE CODIGO_DO_PRODUTO = 1101035 AND QUANTIDADE = 99
GROUP BY CODIGO_DO_PRODUTO;