-- AUTO INCREMENTO (CAMPO IDENTITY)

CREATE TABLE TAB_INDENTITY
(ID INT IDENTITY(1,1) NOT NULL, -- INÍCIO E PASSO
DESCRITO VARCHAR(20) NULL);

INSERT INTO TAB_INDENTITY VALUES
('CLIENTE T');

SELECT * FROM TAB_INDENTITY;

DELETE FROM TAB_INDENTITY
WHERE ID = 6;

-- ALTERANDO INICIO E PASSO

CREATE TABLE TAB_IDENTITY2 (
    ID INT IDENTITY(100,5) NOT NULL, 
    DESCRITOR VARCHAR (20) NULL
);

INSERT INTO TAB_IDENTITY2 VALUES
('CLIENTE T'), ('CLIENTE A'), ('CLIENTE B');

SELECT * FROM TAB_IDENTITY2