-- INCLUINDO MULTIPLOS REGISTROS

-- INCLUINDO DADOS DE OUTRO BANCO

-- VISUALIZANDOS DADOS DE OUTRA BASE
SELECT * FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS

-- COINCIDINDO A ORDEM DOS DOIS BANCOS
SELECT CODIGO_DO_PRODUTO, NOME_DO_PRODUTO, SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA
FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS

-- COINCIDINDO O NOME DAS COLUNAS
SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA
FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS

--INSERINDO
INSERT INTO PRODUTOS SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA
FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS
WHERE CODIGO_DO_PRODUTO <> '1040107'; -- PARA NAO INCLUIR O DADO DUPLICADO

SELECT * FROM PRODUTOS

-- EXERCICIO -- INCLUIR OS CLIENTES DA TABELA RECUPERADA

SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO, IDADE,
GENERO, LIMITE_DE_CREDITO AS LIMITE_CREDITO, VOLUME_DE_COMPRA AS VOLUME_COMPRA, PRIMEIRA_COMPRA
FROM SUCOS_FRUTAS.DBO.TABELA_DE_CLIENTES

INSERT INTO CLIENTES SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO, IDADE,
GENERO, LIMITE_DE_CREDITO AS LIMITE_CREDITO, VOLUME_DE_COMPRA AS VOLUME_COMPRA, PRIMEIRA_COMPRA
FROM SUCOS_FRUTAS.DBO.TABELA_DE_CLIENTES
WHERE CPF NOT IN ('1471156710', '2600586709', '19290992743');

SELECT * FROM CLIENTES;