-- MERGE 

-- ALTERANDO A TABELA APOIO
UPDATE SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS
SET PRECO_DE_LISTA = PRECO_DE_LISTA * 1.20

-- COMPARANDO AS DUAS TABELAS
SELECT
A.CODIGO AS CODIGO_MINHA_TABELA,
PRECO_LISTA AS PRECO_MINHA_TABELA,
B.CODIGO_DO_PRODUTO AS CODIGO_TABELA_APOIO,
B.PRECO_DE_LISTA AS PRECO_TABELA_APOIO
FROM PRODUTOS A
INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
ON A.CODIGO = B.CODIGO_DO_PRODUTO

-- ALTERANDO OS DADOS COM MERGE
MERGE INTO PRODUTOS A
USING SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
ON A.CODIGO = B.CODIGO_DO_PRODUTO
WHEN MATCHED THEN
UPDATE SET A.PRECO_LISTA = B.PRECO_DE_LISTA;