-- TOP

SELECT TOP 5 * FROM TABELA_DE_PRODUTOS;

SELECT TOP 5 * FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Laranja';

-- EXERCÍCIO
SELECT TOP 10 * FROM NOTAS_FISCAIS
WHERE DATA_VENDA = '2017-10-01';

-- ORDER BY

SELECT * FROM TABELA_DE_PRODUTOS
ORDER BY PRECO_DE_LISTA;

SELECT * FROM TABELA_DE_PRODUTOS
ORDER BY PRECO_DE_LISTA DESC;

SELECT * FROM TABELA_DE_PRODUTOS
ORDER BY NOME_DO_PRODUTO;

-- USANDO A QUEBRA
SELECT * FROM TABELA_DE_PRODUTOS
ORDER BY EMBALAGEM, NOME_DO_PRODUTO;

-- EXERCÍCIO

SELECT * FROM TABELA_DE_PRODUTOS
WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limao';

SELECT TOP 1 * FROM ITENS_NOTAS_FISCAIS
WHERE CODIGO_DO_PRODUTO = 1101035
ORDER BY QUANTIDADE DESC;
-- OUTRA FORMA
SELECT * FROM ITENS_NOTAS_FISCAIS
WHERE CODIGO_DO_PRODUTO = (SELECT CODIGO_DO_PRODUTO FROM TABELA_DE_PRODUTOS
                            WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limao')
ORDER BY QUANTIDADE DESC;
