-- TRIGGER

CREATE TABLE TAB_FATURAMENTO
(DATA_VENDA DATE NULL,
TOTAL_VENDA FLOAT);


-- SELECIONANDO AS VENDAS POR DIA
SELECT
TV.DATA_VENDA,
SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA
FROM TABELA_DE_VENDAS TV
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV
ON TV.NUMERO = TIV.NUMERO
GROUP BY DATA_VENDA;

-- COLOCANDO O CONTEUDO DENTRO DA TABELA DE FATURAMENTO
INSERT INTO TAB_FATURAMENTO
SELECT
TV.DATA_VENDA, -- NOME DO CAMPO DEVE SER O MESMO DA TABELA A RECEBER
SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA -- NOME DO CAMPO DEVE SER O MESMO DA TABELA A RECEBER
FROM TABELA_DE_VENDAS TV
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV
ON TV.NUMERO = TIV.NUMERO
GROUP BY DATA_VENDA;

-- ##############################################

-- Estamos rodando o INSERT, depois apagando a tabela que sumariza a venda, 
-- incluindo os dados nela de novo, e fazendo a seleção dela. 
-- Então, eu vou colocar a consulta dela antes, eu vou vê-la antes do INSERT e depois do INSERT

SELECT * FROM TAB_FATURAMENTO;

INSERT INTO TABELA_DE_VENDAS 
VALUES (
    '0109', '2018-05-17', '1471156710', '235', 0.18
);

INSERT INTO TABELA_DE_ITENS_VENDIDOS 
VALUES (
    '0109', '1000889', 150, 10
);

DELETE FROM TAB_FATURAMENTO;

INSERT INTO TAB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;

SELECT * FROM TAB_FATURAMENTO;

-- CRIANDO A TRIGGER
CREATE TRIGGER TG_ITENS_VENDIDOS
ON TABELA_DE_ITENS_VENDIDOS
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
DELETE FROM TAB_FATURAMENTO;
INSERT INTO TAB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;
END