-- IF 

SELECT GETDATE(); -- DIA DE HOJE

SELECT DATENAME(WEEKDAY, GETDATE()); -- DIA DA SEMANA

SELECT GETDATE(), DATEADD(DAY, 5, GETDATE()); -- ADICIONANDO 5 DIAS AO DIA DE HOJE

SELECT DATENAME (WEEKDAY, DATEADD(DAY, 5, GETDATE())); -- DIA DA SEMANA DAQUI A 5 DIAS

DECLARE @DIA_SEMANA VARCHAR(20);
DECLARE @NUMERO_DIAS INT;

SET @NUMERO_DIAS = 20;
SET @DIA_SEMANA = DATENAME (WEEKDAY, DATEADD(DAY, @NUMERO_DIAS, GETDATE()));
PRINT @DIA_SEMANA;

IF @DIA_SEMANA = 'Domingo' OR @DIA_SEMANA = 'Sábado'
	PRINT 'Este dia é fim de semana!';
ELSE
	PRINT 'Este dia é dia de semana';