-- T-SQL
-- DECLARAÇÃO DE VARIAVEIS

--DECLARE @MATRICULA VARCHAR(5);
--DECLARE @NOME VARCHAR(100);
--DECLARE @PERCENTUAL FLOAT;
--DECLARE @DATA DATE;
--DECLARE @FERIAS BIT;
--DECLARE @BAIRRO VARCHAR(50);


--DECLARE @MATRICULA VARCHAR(5), @NOME VARCHAR(100),@PERCENTUAL FLOAT, @DATA DATE, @FERIAS BIT, @BAIRRO VARCHAR(50);

DECLARE @MATRICULA VARCHAR(5), @NOME VARCHAR(100),@PERCENTUAL FLOAT;
DECLARE @DATA DATE, @FERIAS BIT, @BAIRRO VARCHAR(50);

-- EXERCICIO
--DECLARE @NOME VARCHAR(10), @IDADE INT, @DATANASCIMENTO DATE, @CUSTO FLOAT;

--SET @NOME = 'João';
--SET @IDADE = 10;
--SET @DATANASCIMENTO = '2007-01-10';
--SET @CUSTO = 10.23;

--PRINT @NOME;
--PRINT @IDADE;
--PRINT @DATANASCIMENTO;
--PRINT @CUSTO;

-- ATRIBUINDO VALORES

SET @MATRICULA = '00240';
SET @NOME = 'Cláudia Rodrigues';
SET @PERCENTUAL = 0.1;
SET @DATA = '2012-03-12';
SET @FERIAS = 1;
SET @BAIRRO = 'Jardins';

PRINT @MATRICULA;
PRINT @NOME;
PRINT @PERCENTUAL;
PRINT @DATA;
PRINT @FERIAS;
PRINT @BAIRRO;

SET @MATRICULA = '00245';
SET @NOME = 'Roberto Sales';

PRINT @MATRICULA;
PRINT @NOME;
PRINT @PERCENTUAL;
PRINT @DATA;
PRINT @FERIAS;
PRINT @BAIRRO;