-- IF COM SELECT

SELECT * FROM [TABELA DE CLIENTES];

SELECT BAIRRO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES]
GROUP BY BAIRRO;

SELECT SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES]
WHERE BAIRRO = 'Água Santa';

-- SCRIPT USANDO A VARIAVEL @LIMITE_ATUAL
DECLARE @LIMITE_MAXIMO FLOAT;
DECLARE @LIMITE_ATUAL FLOAT;
DECLARE @BAIRRO VARCHAR(20);

SET @LIMITE_MAXIMO = 50000;
SET @BAIRRO = 'Água Santa';
SELECT @LIMITE_ATUAL = SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES]
WHERE BAIRRO = @BAIRRO;

IF @LIMITE_MAXIMO <= @LIMITE_ATUAL
	PRINT 'Valor Estourou';
ELSE
	PRINT 'Valor não estourou';

-- SCRIPT SEM USAR A VARIAVEL @LIMITE_ATUAL
DECLARE @LIMITE_MAXIMO FLOAT;
DECLARE @BAIRRO VARCHAR(20);

SET @LIMITE_MAXIMO = 50000;
SET @BAIRRO = 'Água Santa';

IF @LIMITE_MAXIMO <= (SELECT SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES]
WHERE BAIRRO = @BAIRRO)
	PRINT 'Valor Estourou';
ELSE
	PRINT 'Valor não estourou';
