-- USANDO UPDATE COM FROM

SELECT * FROM PRODUTOS
ORDER BY CODIGO;

SELECT * FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS
ORDER BY CODIGO_DO_PRODUTO;

-- ALTERANDO A TABELA APOIO

UPDATE SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS
SET PRECO_DE_LISTA = PRECO_DE_LISTA * 1.20

-- COMPARANDO AS DUAS TABELAS
SELECT
A.CODIGO AS CODIGO_MINHA_TABELA,
PRECO_LISTA AS PRECO_MINHA_TABELA,
B.CODIGO_DO_PRODUTO AS CODIGO_TABELA_APOIO,
B.PRECO_DE_LISTA AS PRECO_TABELA_APOIO
FROM PRODUTOS A
INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
ON A.CODIGO = B.CODIGO_DO_PRODUTO

-- TRANSFERINDO OS DADOS
UPDATE A
SET A.PRECO_LISTA = B.PRECO_DE_LISTA
FROM PRODUTOS A
INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
ON A.CODIGO = B.CODIGO_DO_PRODUTO

-- EXERCÍCIO
SELECT
V.NOME AS VENDEDOR,
V.BAIRRO AS BAIRRO_VENDEDOR,
C.NOME AS CLIENTE,
C.BAIRRO AS BAIRRO_CLIENTE
FROM VENDEDORES V
INNER JOIN CLIENTES C
ON V.BAIRRO = C.BAIRRO

UPDATE C
SET C.VOLUME_COMPRA = C.VOLUME_COMPRA * 1.3
FROM VENDEDORES V
INNER JOIN CLIENTES C
ON V.BAIRRO = C.BAIRRO
