-- OUTROS TIPOS DE JOIN
-- ANALISANDO BAIRROS COM VENDEDORES E CLIENTES

SELECT COUNT(*) FROM TABELA_DE_CLIENTES;
-- 16 CLIENTES --> 7 CLIENTES POSSUEM VENDEDORES NOS SEUS BAIRROS

SELECT COUNT(*) FROM TABELA_DE_VENDEDORES;
-- 4 VENDEDORES --> 3 VENDEDORES POSSUEM CLIENTES NOS SEUS BAIRROS

SELECT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE,
TC.NOME AS NOME_DO_CLIENTE
FROM 
TABELA_DE_CLIENTES TC
INNER JOIN 
TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO

-- QUAL VENDEDOR NAO TEM CLIENTE NO SEU BAIRRO?

SELECT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE,
TC.NOME AS NOME_DO_CLIENTE
FROM 
TABELA_DE_CLIENTES TC
RIGHT JOIN 
TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO

-- UTILIZANDO FILTRO

SELECT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE,
TC.NOME AS NOME_DO_CLIENTE
FROM 
TABELA_DE_CLIENTES TC
RIGHT JOIN 
TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO
WHERE TC.BAIRRO IS NULL

-- QUAL CLIENTE NAO TEM VENDEDOR NO SEU BAIRRO?

SELECT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE,
TC.NOME AS NOME_DO_CLIENTE
FROM 
TABELA_DE_CLIENTES TC
LEFT JOIN 
TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO
WHERE TV.BAIRRO IS NULL

-- RESPONDENDO AS DUAS PERGUNTAS COM FULL JOIN

SELECT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE,
TC.NOME AS NOME_DO_CLIENTE
FROM 
TABELA_DE_CLIENTES TC
FULL JOIN 
TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO